source 'git@github.com:aferodeveloper/Podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'

use_frameworks!

workspace 'AferoSwiftSDK.xcworkspace'

# MARK: -
# MARK: Prerequisite definitions

XCODE_VERSION = (`xcodebuild -version`.scan /^Xcode\s+(\S+)$/)[0][0]
puts "Using Xcode version: #{XCODE_VERSION}"

def base_pods

    # Else if on XCode 9/Swift 4, use:
    if XCODE_VERSION.start_with?("9")
        pod 'CryptoSwift', '0.7.2'
    else
        pod 'CryptoSwift', '0.7.0'
    end

    pod 'CocoaLumberjack/Swift', '~> 3.2'

    pod 'ReactiveSwift', '~> 1.1', :inhibit_warnings => true
    pod 'PromiseKit/CorePromise', '~> 4.3'
    pod 'HTTPStatusCodes', '~> 3.1'
    pod 'AferoSwiftSDK/AFNetworking', :path => '..'
end

def test_pods
    pod 'Quick', :inhibit_warnings => true
    pod 'Nimble', :inhibit_warnings => true
    pod 'OHHTTPStubs/Swift'
end

# MARK: - Target Linking
# MARK • Base framework

target 'AferoTests' do
    project 'AferoSwiftSDK.xcodeproj'
    platform :ios, '9.3'
    base_pods
    test_pods
end


# MARK: - Subprojects -
# MARK: * AferoLab

target 'AferoLab' do

    project 'AferoLab/AferoLab.xcodeproj'
    
    base_pods
    
    pod 'LKAlertController', '1.12.1'
    pod 'RSEnvironment', '0.0.3'
    pod 'SVProgressHUD', '1.1.3'
    pod 'QRCodeReader.swift', '~> 8.0'
    pod 'LKAlertController', '1.12.1'

end

target 'AferoLabTests' do
  project 'AferoLab/AferoLab.xcodeproj'
  inherit! :search_paths
end

target 'AferoLabUITests' do
  project 'AferoLab/AferoLab.xcodeproj'
  inherit! :search_paths
end

post_install do |installer|

  # List of Pods to use as Swift 3.2
  myTargets = ['AferoSwiftSDK', 'ReactiveSwift']

  installer.pods_project.targets.each do |target|
    if myTargets.include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.2'
      end
    end
  end
end
