source 'git@github.com:aferodeveloper/Podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'

use_frameworks!

workspace 'AferoSwiftSDK.xcworkspace'

# MARK: -
# MARK: Prerequisite definitions

def base_pods

    # If on XCode 8.3/Swift 3, use:
    pod 'CryptoSwift', '0.6.9'
    pod 'CocoaLumberjack/Swift', '3.2.0'
    
    # Else if on XCode 9/Swift 4, use:
    #pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift.git', :branch => 'swift4'
    #pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :commit => 'd9bed4d739d47fee8f17ae918a0665829f2f1736'

    pod 'ReactiveSwift', '~> 1.1', :inhibit_warnings => true
    pod 'PromiseKit', '4.1.3'
    pod 'HTTPStatusCodes', '~> 3.1'
    pod 'AferoSwiftLogging', '1.1.5'
    pod 'AferoSofthub', :inhibit_warnings => true
    pod 'AferoSwiftSDK/AFNetworking', :path => '..'
end

def test_pods
    pod 'Quick', :inhibit_warnings => true
    pod 'Nimble', :inhibit_warnings => true
    pod 'OHHTTPStubs/Swift'
end

# MARK: - Target Linking
# MARK • Base framework

target 'AferoTests' do
    project 'AferoSwiftSDK.xcodeproj'
    platform :ios, '9.3'
    base_pods
    test_pods
end


# MARK: - Subprojects -
# MARK: * AferoLab

target 'AferoLab' do

    project 'AferoLab/AferoLab.xcodeproj'
    
    # If on XCode 8.3/Swift 3, use:
    pod 'CocoaLumberjack/Swift', '3.2.0'
    
    # Else if on XCode 9/Swift 4, use:
    #pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :commit => 'd9bed4d739d47fee8f17ae918a0665829f2f1736'

    pod 'ReactiveSwift', '~> 1.1', :inhibit_warnings => true
    pod 'AferoSwiftSDK/AFNetworking', :path => ".."

    pod 'AferoSofthub', :inhibit_warnings => true

    pod 'HTTPStatusCodes', '~> 3.1'
    pod 'PromiseKit', '4.1.3'
    pod 'LKAlertController', '1.12.1'
    pod 'RSEnvironment', '0.0.3'
    pod 'SVProgressHUD', '1.1.3'
    pod 'QRCodeReader.swift'
    pod 'LKAlertController', '1.12.1'

end

target 'AferoLabTests' do
  project 'AferoLab/AferoLab.xcodeproj'
  inherit! :search_paths
end

target 'AferoLabUITests' do
  project 'AferoLab/AferoLab.xcodeproj'
  inherit! :search_paths
end

