source 'git@github.com:aferodeveloper/Podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'

use_frameworks!

workspace 'AferoSwiftSDK.xcworkspace'

# MARK: -
# MARK: Prerequisite definitions

XCODE_VERSION = (`xcodebuild -version`.scan /^Xcode\s+(\S+)$/)[0][0]
puts "Using Xcode version: #{XCODE_VERSION}"

def base_pods
    pod 'CryptoSwift', '1.4.0'

    pod 'CocoaLumberjack/Swift', '3.5.2', :inhibit_warnings => true

    pod 'ReactiveSwift', '5.0.0', :inhibit_warnings => true
    pod 'PromiseKit/CorePromise', '4.5.1'
    pod 'HTTPStatusCodes', '~> 3.2'
    pod 'AFNetworking/NSURLSession', :inhibit_warnings => true
    pod 'AferoSwiftSDK/AFNetworking', :path => '..'
end

def test_pods
    pod 'Quick', :inhibit_warnings => true
    pod 'Nimble', :inhibit_warnings => true
    pod 'OHHTTPStubs/Swift'
end

# MARK: - Target Linking
# MARK • Base framework

target 'AferoTests' do
    project 'AferoSwiftSDK.xcodeproj'
    platform :ios, '9.3'
    base_pods
    test_pods
end


# MARK: - Subprojects -
# MARK: * AferoLab

target 'AferoLab' do

    project 'AferoLab/AferoLab.xcodeproj'
    
    base_pods
    
    pod 'LKAlertController', '1.12.2'
    pod 'RSEnvironment', '0.0.3'
    pod 'SVProgressHUD', '1.1.3', :inhibit_warnings => true
    pod 'QRCodeReader.swift', '~> 10.0.0'
    pod 'LKAlertController', '1.12.2'
    pod 'AppAuth', '1.4.0'
    pod 'AferoSofthub', :path => '../../AferoSofthub'

end

target 'AferoLabTests' do
  project 'AferoLab/AferoLab.xcodeproj'
  inherit! :search_paths
end

target 'AferoLabUITests' do
  project 'AferoLab/AferoLab.xcodeproj'
  inherit! :search_paths
end

# MARK: * Bubba

target 'Bubba' do
    project 'Bubba/Bubba.xcodeproj'
    base_pods
    pod 'QRCode', '~> 2.0'
    pod 'SVProgressHUD', '1.1.3', :inhibit_warnings => true
end

post_install do |installer|

#  # List of Pods to use as Swift 4.2
#  myTargets = ['AferoSwiftSDK']
#
#  installer.pods_project.targets.each do |target|
#    if myTargets.include? target.name
#      target.build_configurations.each do |config|
#        config.build_settings['SWIFT_VERSION'] = '4.2'
#      end
#    end
#  end
end
